---
title: "EDA Stranger Things"
output:
  html_notebook:
    toc: yes
    toc_float: yes
  html_document:
    df_print: paged
    toc: yes
    toc_float: yes
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(here)
theme_set(theme_bw())
```


```{r}
all_series = read_csv(here("data/series_from_imdb.csv.zip"), 
                      col_types = "ccdcdcdddddddddddd") 

glimpse(all_series)

```

```{r}
all_series %>% 
    count(series_name)
```

```{r}
aang = all_series %>% 
    filter(series_name == "Avatar: A Lenda de Aang")
```

```{r}
kora = all_series %>% 
    filter(series_name == "Avatar: A Lenda de Korra")
```

```{r}
aang %>% 
  ggplot(aes(x = season_ep, y = UserRating)) +
  facet_wrap(~ season, ncol = 1)+ 
  geom_line()
```

```{r}
kora %>% 
  ggplot(aes(x = season_ep, y = UserRating)) +
  facet_wrap(~ season, ncol = 1)+ 
  geom_line()
```

## Possíveis Perguntas

A lenda De Aang foi melhor avaliada que a lenda de Kora?
Qual a temporada das duas séries foi melhor avaliada?
Existem alguma correlação entre as avaliações da primeira  e última temporada de cada séries?
E Existe correção entre as duas séries em relação a avaliação da primeira e última temporada?


